# Generated by Django 3.1.4 on 2020-12-03 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paylater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('room', 'Room'), ('shop', 'Shop'), ('apartment', 'Apartment')], max_length=255)),
                ('request_accepted_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='paylater_request',
            fields=[
                ('paylater_request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_type', models.CharField(choices=[('room', 'Room'), ('shop', 'Shop'), ('apartment', 'Apartment')], max_length=255)),
                ('admin_status', models.CharField(choices=[('accepted', 'Aceepted'), ('declined', 'Declined'), ('pending', 'Pending')], max_length=255)),
                ('seller_status', models.CharField(choices=[('accepted', 'Aceepted'), ('declined', 'Declined'), ('pending', 'Pending')], max_length=255)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
    ]
