# Generated by Django 3.1.4 on 2020-12-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('seller', '0001_initial'),
        ('products', '0001_initial'),
        ('paylater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paylater_request',
            name='apartment_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='products.apartments'),
        ),
        migrations.AddField(
            model_name='paylater_request',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='paylater_request',
            name='room_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='products.rooms'),
        ),
        migrations.AddField(
            model_name='paylater_request',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seller.seller'),
        ),
        migrations.AddField(
            model_name='paylater_request',
            name='shop_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='products.shops'),
        ),
        migrations.AddField(
            model_name='paylater',
            name='apartment_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='products.apartments'),
        ),
        migrations.AddField(
            model_name='paylater',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='paylater',
            name='paylater_request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paylater.paylater_request'),
        ),
        migrations.AddField(
            model_name='paylater',
            name='room_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='products.rooms'),
        ),
        migrations.AddField(
            model_name='paylater',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seller.seller'),
        ),
        migrations.AddField(
            model_name='paylater',
            name='shop_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='products.shops'),
        ),
    ]
