# Generated by Django 3.1.4 on 2021-02-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coupons',
            fields=[
                ('coupoun_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateField()),
                ('expiry_date', models.DateField()),
                ('expired', models.BooleanField(default=False)),
                ('admin_coupon', models.BooleanField(default=False)),
                ('coupon_type', models.CharField(choices=[('discount', 'discount'), ('off_price', 'off_price')], max_length=255)),
                ('off', models.IntegerField(default=0)),
                ('min_price', models.IntegerField(default=0)),
                ('max_off_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
