# Generated by Django 3.1.4 on 2021-02-06 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20210206_1002'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='coupons',
            fields=[
                ('coupoun_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('life', models.IntegerField(default=2)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('admin_coupon', models.BooleanField(default=False)),
                ('coupon_type', models.CharField(choices=[('discount', 'discount'), ('off_price', 'off_price')], max_length=255)),
                ('off', models.IntegerField(default=0)),
                ('min_price', models.IntegerField(blank=True, null=True)),
                ('max_off_price', models.IntegerField(blank=True, null=True)),
                ('coupoun_apartments', models.ManyToManyField(blank=True, to='products.apartments')),
                ('coupoun_rooms', models.ManyToManyField(blank=True, to='products.rooms')),
                ('coupoun_shops', models.ManyToManyField(blank=True, to='products.shops')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ManyToManyField(blank=True, related_name='used_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
