# Generated by Django 3.1.4 on 2021-02-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='coupoun_apartments',
            field=models.ManyToManyField(blank=True, to='products.apartments'),
        ),
        migrations.AddField(
            model_name='coupons',
            name='coupoun_rooms',
            field=models.ManyToManyField(blank=True, to='products.rooms'),
        ),
        migrations.AddField(
            model_name='coupons',
            name='coupoun_shops',
            field=models.ManyToManyField(blank=True, to='products.shops'),
        ),
    ]
