# Generated by Django 3.1.4 on 2021-02-07 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20210206_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='valid_from',
            field=models.DateField(default=datetime.date(2021, 2, 7)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupons',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2021, 2, 7)),
            preserve_default=False,
        ),
    ]
