# Generated by Django 3.1.4 on 2021-02-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20210207_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='life',
        ),
    ]
