# Generated by Django 3.1.4 on 2021-04-03 06:58

import complaint.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0019_auto_20210321_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_complaints',
            fields=[
                ('complaint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('photo1', models.ImageField(blank=True, null=True, upload_to=complaint.models.upload_to_room_complaint, verbose_name='Image')),
                ('customer_fullfilled', models.BooleanField(default=False)),
                ('seller_fullfilled', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_room_customer_id', to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_room_id', to='products.rooms')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_room_seller_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
