# Generated by Django 3.1.4 on 2021-04-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_room_complaints_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_complaints',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
