# Generated by Django 3.1.4 on 2021-04-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_room_complaints_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_complaints',
            name='seller_name',
            field=models.CharField(default='prateek', max_length=255),
            preserve_default=False,
        ),
    ]
