# Generated by Django 3.1.4 on 2021-04-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_room_complaints_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_complaints',
            name='customer_contact',
            field=models.CharField(default='cjdjee@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room_complaints',
            name='seller_contact',
            field=models.CharField(default='fjeje@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
