# Generated by Django 3.1.4 on 2021-04-05 04:40

import complaint.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint', '0007_apartment_complaints_shop_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to=complaint.models.upload_to_me, verbose_name='Image')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_apartment_customer_id', to=settings.AUTH_USER_MODEL)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_apartment_seller_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='apartment_complaints',
            name='messages',
            field=models.ManyToManyField(related_name='apartment_message', to='complaint.message_class'),
        ),
        migrations.AddField(
            model_name='room_complaints',
            name='messages',
            field=models.ManyToManyField(related_name='room_message', to='complaint.message_class'),
        ),
        migrations.AddField(
            model_name='shop_complaints',
            name='messages',
            field=models.ManyToManyField(related_name='shop_message', to='complaint.message_class'),
        ),
    ]
