# Generated by Django 3.1.4 on 2021-04-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_auto_20210405_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_class',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
