# Generated by Django 3.1.4 on 2021-04-05 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint', '0009_message_class_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_class',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='message_class',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='message_class',
            name='receiver_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='message_receiver_id', to='user.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message_class',
            name='sender_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='message_sender_id', to='user.customuser'),
            preserve_default=False,
        ),
    ]
