# Generated by Django 3.1.4 on 2021-04-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_auto_20210405_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_class',
            old_name='photo1',
            new_name='photo',
        ),
    ]
