# Generated by Django 3.1.4 on 2021-04-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0011_auto_20210405_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment_complaints',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='room_complaints',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='shop_complaints',
            name='reply',
        ),
    ]
