# Generated by Django 3.1.4 on 2021-04-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0012_auto_20210405_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment_complaints',
            name='seller_contact',
        ),
        migrations.RemoveField(
            model_name='apartment_complaints',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='room_complaints',
            name='seller_contact',
        ),
        migrations.RemoveField(
            model_name='room_complaints',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='shop_complaints',
            name='seller_contact',
        ),
        migrations.RemoveField(
            model_name='shop_complaints',
            name='seller_name',
        ),
    ]
