# Generated by Django 3.1.4 on 2021-04-05 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint', '0013_auto_20210405_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment_complaints',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='apartment_complaints',
            name='seller_id',
            field=models.ManyToManyField(related_name='apartment_id_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='room_complaints',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='room_complaints',
            name='seller_id',
            field=models.ManyToManyField(related_name='room_id_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='shop_complaints',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='shop_complaints',
            name='seller_id',
            field=models.ManyToManyField(related_name='shop_id_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
