# Generated by Django 3.1.4 on 2021-04-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0015_auto_20210405_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_class',
            old_name='seller_id',
            new_name='receiver_id',
        ),
    ]
