# Generated by Django 3.1.4 on 2021-04-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_auto_20210326_1734'),
        ('complaint', '0016_auto_20210405_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment_complaints',
            name='apartment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_apartmentbooking_id', to='bookings.apartmentbookings'),
        ),
        migrations.AlterField(
            model_name='room_complaints',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_roombooking_id', to='bookings.roombookings'),
        ),
        migrations.AlterField(
            model_name='shop_complaints',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_shopbooking_id', to='bookings.shopbookings'),
        ),
    ]
