# Generated by Django 3.1.4 on 2020-12-03 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='refund_apartment',
            fields=[
                ('refund_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('refund_request_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=255)),
                ('refund_receipt', models.FileField(upload_to='refund_receipt/apartments/% Y/% m/% d/')),
                ('refund_amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='refund_room',
            fields=[
                ('refund_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('refund_request_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=255)),
                ('refund_receipt', models.FileField(upload_to='refund_receipt/rooms/% Y/% m/% d/')),
                ('refund_amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='refund_shop',
            fields=[
                ('refund_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('refund_request_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=255)),
                ('refund_receipt', models.FileField(upload_to='refund_receipt/shops/% Y/% m/% d/')),
                ('refund_amount', models.BigIntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seller.seller')),
            ],
        ),
    ]
