# Generated by Django 3.1.4 on 2020-12-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='date_jointed',
            new_name='date_joined',
        ),
        migrations.AlterField(
            model_name='seller_rating_and_reviews',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='seller_rating_and_reviews',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seller.seller'),
        ),
    ]
