# Generated by Django 3.1.4 on 2020-12-03 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shops',
            fields=[
                ('shop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('furniture', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('trust_points', models.BigIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_verified', models.DateTimeField()),
                ('images', models.ImageField(upload_to='images/shops')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='shop_rating_and_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reviews', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.shops')),
            ],
        ),
        migrations.CreateModel(
            name='shop_facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.TextField()),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.shops')),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('furniture', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('capacity', models.IntegerField()),
                ('trust_points', models.BigIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_verified', models.DateTimeField()),
                ('images', models.ImageField(upload_to='images/rooms')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='room_rating_and_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reviews', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='room_facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.TextField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='apartments',
            fields=[
                ('apartment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('furniture', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('BHK', models.IntegerField()),
                ('trust_points', models.BigIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_verified', models.DateTimeField()),
                ('images', models.ImageField(upload_to='images/apartments')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='apartment_rating_and_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reviews', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.apartments')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='apartment_facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.TextField()),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.apartments')),
            ],
        ),
    ]
