# Generated by Django 3.1.4 on 2020-12-21 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.PositiveBigIntegerField()),
                ('owner_discount', models.IntegerField(default=0)),
                ('company_discount', models.IntegerField(default=0)),
                ('final_price', models.PositiveBigIntegerField(default=models.PositiveBigIntegerField())),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('furniture', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('capacity', models.IntegerField()),
                ('trust_points', models.BigIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_verified', models.DateTimeField(default=None)),
                ('photo1', models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to, verbose_name='Image')),
                ('photo2', models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to, verbose_name='Image')),
                ('photo3', models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to, verbose_name='Image')),
                ('booked', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('facilities', models.TextField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_owner_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='shops',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.PositiveBigIntegerField()),
                ('owner_discount', models.IntegerField(default=0)),
                ('company_discount', models.IntegerField(default=0)),
                ('final_price', models.PositiveBigIntegerField(default=models.PositiveBigIntegerField())),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('furniture', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('trust_points', models.BigIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_verified', models.DateTimeField(default=None)),
                ('photo1', models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_shops, verbose_name='Image')),
                ('photo2', models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_shops, verbose_name='Image')),
                ('photo3', models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_shops, verbose_name='Image')),
                ('booked', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('facilities', models.TextField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_owner_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='shop_rating_and_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reviews', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_customer', to=settings.AUTH_USER_MODEL)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop', to='products.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='room_rating_and_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reviews', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_customer', to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room', to='products.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='apartments',
            fields=[
                ('apartment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.PositiveBigIntegerField()),
                ('owner_discount', models.IntegerField(default=0)),
                ('company_discount', models.IntegerField(default=0)),
                ('final_price', models.PositiveBigIntegerField(default=models.PositiveBigIntegerField())),
                ('length', models.IntegerField()),
                ('breadth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('furniture', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('BHK', models.IntegerField()),
                ('trust_points', models.BigIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_verified', models.DateTimeField(default=None)),
                ('photo1', models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_apartments, verbose_name='Image')),
                ('photo2', models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_apartments, verbose_name='Image')),
                ('photo3', models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_apartments, verbose_name='Image')),
                ('booked', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('facilities', models.TextField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartment_owner_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='apartment_rating_and_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reviews', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartment', to='products.rooms')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartment_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
