# Generated by Django 3.1.4 on 2020-12-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='facilities',
            new_name='facility',
        ),
    ]
