# Generated by Django 3.1.4 on 2020-12-25 11:12

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201224_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100),
        ),
    ]
