# Generated by Django 3.1.4 on 2020-12-30 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201230_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='bookedtill',
            field=models.DateField(default=datetime.datetime(2020, 12, 29, 5, 41, 23, 517635), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='bookedtill',
            field=models.DateField(default=datetime.datetime(2020, 12, 29, 5, 41, 23, 517635), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='bookedtill',
            field=models.DateField(default=datetime.datetime(2020, 12, 29, 5, 41, 23, 517635), verbose_name='Date'),
        ),
    ]
