# Generated by Django 3.1.4 on 2021-02-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210205_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='book1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book10',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book11',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book12',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book13',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book14',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book15',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book16',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book17',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book18',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book19',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book20',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book7',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book8',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='book9',
            field=models.DateField(blank=True, null=True),
        ),
    ]
