# Generated by Django 3.1.4 on 2021-02-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210218_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='fans',
            field=models.IntegerField(default=0),
        ),
    ]
