# Generated by Django 3.1.4 on 2020-12-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201230_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='bookedtill',
            field=models.DateField(blank=True, null=True, verbose_name='Booked_till_Date'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='bookedtill',
            field=models.DateField(blank=True, null=True, verbose_name='Booked_till_Date'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='bookedtill',
            field=models.DateField(blank=True, null=True, verbose_name='Booked_till_Date'),
        ),
    ]
