# Generated by Django 3.1.4 on 2020-12-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201221_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='category',
            field=models.CharField(default='5 STAR ROOM', max_length=255),
        ),
        migrations.AddField(
            model_name='apartments',
            name='city',
            field=models.CharField(default='adad', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartments',
            name='country',
            field=models.CharField(default='ada', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartments',
            name='landmark',
            field=models.CharField(default='adad', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartments',
            name='pincode',
            field=models.CharField(default='ad', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartments',
            name='state',
            field=models.CharField(default='ada', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='category',
            field=models.CharField(default='5 STAR ROOM', max_length=255),
        ),
        migrations.AddField(
            model_name='rooms',
            name='city',
            field=models.CharField(default='ada', max_length=255),
        ),
        migrations.AddField(
            model_name='rooms',
            name='country',
            field=models.CharField(default='ada', max_length=255),
        ),
        migrations.AddField(
            model_name='rooms',
            name='landmark',
            field=models.CharField(default='ada', max_length=255),
        ),
        migrations.AddField(
            model_name='rooms',
            name='pincode',
            field=models.CharField(default='ada', max_length=255),
        ),
        migrations.AddField(
            model_name='rooms',
            name='state',
            field=models.CharField(default='ada', max_length=255),
        ),
        migrations.AddField(
            model_name='shops',
            name='category',
            field=models.CharField(default='5 STAR ROOM', max_length=255),
        ),
        migrations.AddField(
            model_name='shops',
            name='city',
            field=models.CharField(default='adwa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='country',
            field=models.CharField(default='ada', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='landmark',
            field=models.CharField(default='adad', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='pincode',
            field=models.CharField(default='adad', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='state',
            field=models.CharField(default='adaw', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartments',
            name='date_verified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='location',
            field=models.TextField(default='asdasd'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='date_verified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
