# Generated by Django 3.1.4 on 2020-12-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201225_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='address',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='geolocation',
        ),
    ]
