# Generated by Django 3.1.4 on 2021-02-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shops_fans'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='balcony',
            field=models.IntegerField(default=0),
        ),
    ]
