# Generated by Django 3.1.4 on 2021-02-07 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210206_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='book11',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='book12',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='book13',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='book14',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='book15',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='book16',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='book17',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='book18',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='book19',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='book20',
        ),
    ]
