# Generated by Django 3.1.4 on 2021-02-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210207_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='seller_price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
