# Generated by Django 3.1.4 on 2020-12-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201222_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='landmark',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='pincode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shops',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
