# Generated by Django 3.1.4 on 2021-01-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201230_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='coupon_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartments',
            name='seller_coupons',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='coupon_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='seller_coupons',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='coupon_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='seller_coupons',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
