# Generated by Django 3.1.4 on 2020-12-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201225_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='title',
            field=models.CharField(default='title', max_length=255),
            preserve_default=False,
        ),
    ]
