# Generated by Django 3.1.4 on 2021-02-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210210_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='pausebooking',
            field=models.BooleanField(default=False),
        ),
    ]
