# Generated by Django 3.1.4 on 2021-02-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210218_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartments',
            old_name='facilities',
            new_name='facility',
        ),
        migrations.RenameField(
            model_name='apartments',
            old_name='removable_TV',
            new_name='removable_house_TV',
        ),
        migrations.AddField(
            model_name='apartments',
            name='cost_laundry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartments',
            name='sofa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartments',
            name='total_AC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartments',
            name='total_TV',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartments',
            name='total_beds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apartments',
            name='total_cooler',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartments',
            name='total_geyser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='TV',
            field=models.BooleanField(default=False),
        ),
    ]
