# Generated by Django 3.1.4 on 2021-01-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210103_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartments',
            old_name='seller_coupons',
            new_name='seller_coupon',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='seller_coupons',
            new_name='seller_coupon',
        ),
        migrations.RenameField(
            model_name='shops',
            old_name='seller_coupons',
            new_name='seller_coupon',
        ),
    ]
