# Generated by Django 3.1.4 on 2020-12-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201222_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='fake_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='fake_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shops',
            name='fake_discount',
            field=models.IntegerField(default=0),
        ),
    ]
