# Generated by Django 3.1.4 on 2021-02-15 11:11

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rooms_pausebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='nearby_restaurant1',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='nearby_restaurant2',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='seller_coupon',
        ),
        migrations.AddField(
            model_name='rooms',
            name='address_proof',
            field=models.FileField(default='/address_proof/rooms/default.pdf', upload_to=products.models.upload_file_to),
        ),
    ]
