# Generated by Django 3.1.4 on 2021-01-07 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_auto_20210103_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='cart',
        ),
        migrations.AddField(
            model_name='apartments',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, related_name='apartment_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='apartments',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='apartments',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='apartment_wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='cart',
        ),
        migrations.AddField(
            model_name='rooms',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, related_name='room_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='rooms',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='room_wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='shops',
            name='cart',
        ),
        migrations.AddField(
            model_name='shops',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, related_name='shop_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='shops',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='shops',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='shop_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
