# Generated by Django 3.1.4 on 2021-02-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210218_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='cost_refridgerator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartments',
            name='house_refridgerator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartments',
            name='removable_house_refridgerator',
            field=models.BooleanField(default=False),
        ),
    ]
