# Generated by Django 3.1.4 on 2020-12-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201225_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='cost_TV',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartments',
            name='cost_electricity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartments',
            name='cost_geyser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartments',
            name='cost_water',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartments',
            name='cost_wifi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartments',
            name='currency',
            field=models.CharField(default='Rs', max_length=200),
        ),
        migrations.AddField(
            model_name='rooms',
            name='cost_TV',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='cost_breakfast',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='cost_dinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='cost_electricity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='cost_geyser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='cost_lunch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='cost_water',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='cost_wifi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='currency',
            field=models.CharField(default='Rs', max_length=200),
        ),
        migrations.AddField(
            model_name='shops',
            name='cost_electricity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shops',
            name='cost_water',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shops',
            name='cost_wifi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shops',
            name='currency',
            field=models.CharField(default='Rs', max_length=200),
        ),
    ]
