# Generated by Django 3.1.4 on 2021-01-07 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_auto_20210107_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='cart',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
