# Generated by Django 3.1.4 on 2021-01-07 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_auto_20210107_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, related_name='apartment_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
