# Generated by Django 3.1.4 on 2021-02-20 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_apartments_fans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='bookedtill',
            field=models.DateField(default=datetime.date(2000, 1, 1), null=True, verbose_name='Booked_till_Date'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='bookedtill',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Booked_till_Date'),
        ),
    ]
