# Generated by Django 3.1.4 on 2021-02-20 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210220_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='bookedtill',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Booked_till_Date'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='bookedtill',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Booked_till_Date'),
        ),
    ]
