# Generated by Django 3.1.4 on 2021-01-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210107_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='apartment_cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shops',
            name='shop_cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='apartments',
            name='cart',
        ),
        migrations.AddField(
            model_name='apartments',
            name='cart',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='apartments',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='apartments',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='cart',
        ),
        migrations.AddField(
            model_name='rooms',
            name='cart',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='rooms',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='shops',
            name='cart',
        ),
        migrations.AddField(
            model_name='shops',
            name='cart',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='shops',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='shops',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
