# Generated by Django 3.1.4 on 2021-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210109_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='cart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='wishlist',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='cart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='wishlist',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shops',
            name='cart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shops',
            name='wishlist',
            field=models.IntegerField(default=0),
        ),
    ]
