# Generated by Django 3.1.4 on 2021-02-20 07:51

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210220_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment_rating_and_reviews',
            name='photo1',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_roomreviews),
        ),
        migrations.AddField(
            model_name='apartment_rating_and_reviews',
            name='photo2',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_roomreviews),
        ),
        migrations.AddField(
            model_name='apartment_rating_and_reviews',
            name='photo3',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_roomreviews),
        ),
        migrations.AddField(
            model_name='room_rating_and_reviews',
            name='photo1',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_roomreviews),
        ),
        migrations.AddField(
            model_name='room_rating_and_reviews',
            name='photo2',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_roomreviews),
        ),
        migrations.AddField(
            model_name='room_rating_and_reviews',
            name='photo3',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_roomreviews),
        ),
        migrations.AddField(
            model_name='shop_rating_and_reviews',
            name='photo1',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_roomreviews),
        ),
        migrations.AddField(
            model_name='shop_rating_and_reviews',
            name='photo2',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_roomreviews),
        ),
        migrations.AddField(
            model_name='shop_rating_and_reviews',
            name='photo3',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_roomreviews),
        ),
    ]
