# Generated by Django 3.1.4 on 2021-01-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210111_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='address',
        ),
        migrations.RemoveField(
            model_name='apartments',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='address',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='apartments',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='apartments',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='rooms',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='rooms',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='shops',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='shops',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
