# Generated by Django 3.1.4 on 2020-12-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201226_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment_rating_and_reviews',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='shop_rating_and_reviews',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
