# Generated by Django 3.1.4 on 2021-02-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210220_0751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='room_rating_and_reviews',
        ),
    ]
