# Generated by Django 3.1.4 on 2021-02-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210222_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='TV',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shops',
            name='cost_TV',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shops',
            name='removable_TV',
            field=models.BooleanField(default=False),
        ),
    ]
