# Generated by Django 3.1.4 on 2021-02-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210222_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='cooler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shops',
            name='cost_cooler',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shops',
            name='removable_cooler',
            field=models.BooleanField(default=False),
        ),
    ]
