# Generated by Django 3.1.4 on 2020-12-26 07:03

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20201226_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='apartment_type',
            field=models.CharField(default='flat', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartments',
            name='balcony',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartments',
            name='bed_type',
            field=models.CharField(default='double', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartments',
            name='floor_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apartments',
            name='photo6',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to_apartments, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='total_floors',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apartments',
            name='total_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apartments',
            name='washroom',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apartments',
            name='windows',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rooms',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='bed_type',
            field=models.CharField(default='single', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='fans',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rooms',
            name='floor_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rooms',
            name='separate_washroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='windows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shops',
            name='floor_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shops',
            name='total_floors',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shops',
            name='total_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shops',
            name='washroom',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shops',
            name='windows',
            field=models.IntegerField(default=1),
        ),
    ]
