# Generated by Django 3.1.4 on 2021-02-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210222_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='removable_laundry',
            field=models.BooleanField(default=False),
        ),
    ]
