# Generated by Django 3.1.4 on 2020-12-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201226_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='currency',
            field=models.CharField(default='₹', max_length=200),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='currency',
            field=models.CharField(default='₹', max_length=200),
        ),
        migrations.AlterField(
            model_name='shops',
            name='currency',
            field=models.CharField(default='₹', max_length=200),
        ),
    ]
