# Generated by Django 3.1.4 on 2021-02-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_apartments_removable_laundry'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='gender',
            field=models.CharField(default='Any', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='gender',
            field=models.CharField(default='Any', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='gender',
            field=models.CharField(default='Any', max_length=255),
            preserve_default=False,
        ),
    ]
