# Generated by Django 3.1.4 on 2020-12-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20201226_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='nonveg_food',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='veg_food',
            field=models.BooleanField(default=True),
        ),
    ]
