# Generated by Django 3.1.4 on 2021-03-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210228_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='net_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='net_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shops',
            name='net_discount',
            field=models.IntegerField(default=0),
        ),
    ]
