# Generated by Django 3.1.4 on 2020-12-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20201226_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
