# Generated by Django 3.1.4 on 2020-12-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20201227_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='building_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartments',
            name='cctv_building',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='building_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='cctv_building',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shops',
            name='building_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shops',
            name='cctv_building',
            field=models.BooleanField(default=False),
        ),
    ]
