# Generated by Django 3.1.4 on 2021-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210525_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='reviews',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='reviews',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='shops',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='shops',
            name='reviews',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
    ]
