# Generated by Django 3.1.4 on 2020-12-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_rooms_guest_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='minmax_apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_price', models.IntegerField()),
                ('min_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='minmax_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_price', models.IntegerField()),
                ('min_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='minmax_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_price', models.IntegerField()),
                ('min_price', models.IntegerField()),
            ],
        ),
    ]
