# Generated by Django 3.1.4 on 2021-05-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210525_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='guest_policy',
            field=models.TextField(),
        ),
    ]
