# Generated by Django 3.1.4 on 2021-05-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20210528_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='removable_AC',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='food_policy',
            field=models.TextField(),
        ),
    ]
