# Generated by Django 3.1.4 on 2021-05-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20210528_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
