# Generated by Django 3.1.4 on 2021-05-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20210529_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='total_beds',
            field=models.IntegerField(default=1),
        ),
    ]
