# Generated by Django 3.1.4 on 2021-05-30 05:52

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_rooms_total_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='video',
            field=models.ImageField(default='/videos/apartments/11.mp4', upload_to=products.models.upload_to_video_apartment, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='video',
            field=models.ImageField(default='/videos/rooms/11.mp4', upload_to=products.models.upload_to_video_room, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='shops',
            name='video',
            field=models.ImageField(default='/videos/shops/11.mp4', upload_to=products.models.upload_to_video_shop, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='photo1',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to, verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='photo2',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to, verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='photo3',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to, verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='photo4',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to, verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='photo5',
            field=models.ImageField(default='/images/rooms/default.jpg', upload_to=products.models.upload_to, verbose_name='Image 5'),
        ),
    ]
