# Generated by Django 3.1.4 on 2021-05-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20210530_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
