# Generated by Django 3.1.4 on 2021-01-07 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_auto_20210107_0750'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.customuser')),
                ('apartment_wishlist', models.ManyToManyField(blank=True, null=True, related_name='wishlist_apartment', to='products.apartments')),
                ('room_wishlist', models.ManyToManyField(blank=True, null=True, related_name='wishlist_room', to='products.rooms')),
                ('shop_wishlist', models.ManyToManyField(blank=True, null=True, related_name='wishlist_shop', to='products.shops')),
            ],
        ),
    ]
