# Generated by Django 3.1.4 on 2021-02-18 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.customuser')),
                ('items', models.IntegerField(default=0)),
                ('apartment_wishlist', models.ManyToManyField(blank=True, related_name='wishlist_apartment', to='products.apartments')),
                ('room_wishlist', models.ManyToManyField(blank=True, related_name='wishlist_room', to='products.rooms')),
                ('shop_wishlist', models.ManyToManyField(blank=True, related_name='wishlist_shop', to='products.shops')),
            ],
        ),
    ]
