# Generated by Django 3.1.4 on 2021-01-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210107_0750'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='apartment_wishlist',
            field=models.ManyToManyField(related_name='wishlist_apartment', to='products.apartments'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='room_wishlist',
            field=models.ManyToManyField(related_name='wishlist_room', to='products.rooms'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='shop_wishlist',
            field=models.ManyToManyField(related_name='wishlist_shop', to='products.shops'),
        ),
    ]
