# Generated by Django 3.1.4 on 2021-01-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210107_0750'),
        ('wishlist', '0002_auto_20210109_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='apartment_wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_apartment', to='products.apartments'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='room_wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_room', to='products.rooms'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='shop_wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_shop', to='products.shops'),
        ),
    ]
