# Generated by Django 3.1.4 on 2021-01-10 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_auto_20210109_1238'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.customuser')),
                ('apartment_cart', models.ManyToManyField(blank=True, related_name='cart_apartment', to='products.apartments')),
                ('room_cart', models.ManyToManyField(blank=True, related_name='cart_room', to='products.rooms')),
                ('shop_cart', models.ManyToManyField(blank=True, related_name='cart_shop', to='products.shops')),
            ],
        ),
    ]
