# Generated by Django 3.1.4 on 2021-01-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.IntegerField(default=0),
        ),
    ]
