# Generated by Django 3.1.4 on 2020-12-20 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='customUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_seller', models.BooleanField(default=False)),
                ('profile_completed', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_jointed', models.DateTimeField(auto_now_add=True)),
                ('removed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='customUser_profile',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.customuser')),
                ('mobile', models.CharField(max_length=255, unique=True)),
                ('aadhar', models.CharField(max_length=255)),
                ('alternate_mobile', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='images/profile_pics/customer')),
            ],
        ),
        migrations.CreateModel(
            name='seller_bank_details',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.customuser')),
                ('account_no', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_address', models.TextField()),
                ('IFSC_code', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], max_length=255)),
                ('total_due_payment', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='seller_rating_and_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reviews', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_id', to=settings.AUTH_USER_MODEL)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
