# Generated by Django 3.1.4 on 2021-01-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser_profile',
            name='alternate_mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
