# Generated by Django 3.1.4 on 2020-12-20 11:54

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser_profile',
            name='photo',
            field=models.ImageField(default='/images/profile_pics/default.jpg', upload_to=user.models.upload_to, verbose_name='Image'),
        ),
    ]
