# Generated by Django 3.1.4 on 2021-02-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_bank_details',
            name='commission',
            field=models.IntegerField(default=0),
        ),
    ]
