# Generated by Django 3.1.4 on 2020-12-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201220_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser_profile',
            name='country_code',
            field=models.CharField(default='+91', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser_profile',
            name='alternate_mobile',
            field=models.CharField(default='00000000000', max_length=255),
        ),
    ]
