# Generated by Django 3.1.4 on 2021-03-27 06:49

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser_profile',
            name='aadhar',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser_profile',
            name='mobile',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser_profile',
            name='photo',
            field=models.ImageField(upload_to=user.models.upload_to, verbose_name='Image'),
        ),
    ]
