# Generated by Django 3.1.4 on 2020-12-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201220_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser_profile',
            name='mobile',
            field=models.CharField(max_length=255),
        ),
    ]
