# Generated by Django 3.1.4 on 2021-03-27 06:59

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210327_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser_profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_to, verbose_name='Image'),
        ),
    ]
