# Generated by Django 3.1.4 on 2021-01-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210121_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_bank_details',
            name='currency',
            field=models.CharField(default='₹', max_length=200),
        ),
    ]
