# Generated by Django 3.1.4 on 2021-04-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210327_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser_profile',
            name='aadhar',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
