# Generated by Django 3.1.4 on 2020-12-21 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201220_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser_profile',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
