# Generated by Django 3.1.4 on 2021-04-24 08:21

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210406_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser_profile',
            name='back',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_to_front, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='customuser_profile',
            name='front',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_to_front, verbose_name='Image'),
        ),
    ]
