# Generated by Django 3.1.4 on 2021-05-24 16:09

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210424_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser_profile',
            name='back',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_to_front, verbose_name='Identification proof back'),
        ),
        migrations.AlterField(
            model_name='customuser_profile',
            name='front',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_to_front, verbose_name='Identification proof front'),
        ),
    ]
