# Generated by Django 3.1.4 on 2020-12-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('cartandwish', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='apartment_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.apartments'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='room_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.rooms'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='shop_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.shops'),
        ),
        migrations.AddField(
            model_name='cart',
            name='apartment_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.apartments'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='room_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.rooms'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shop_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.shops'),
        ),
    ]
