# Generated by Django 3.1.4 on 2021-01-01 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20201230_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopBookings',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_from', models.DateField()),
                ('booked_till', models.DateField()),
                ('duration', models.IntegerField()),
                ('currency', models.CharField(max_length=255)),
                ('cost', models.BigIntegerField()),
                ('price_to_be_paid', models.BigIntegerField()),
                ('discount', models.IntegerField()),
                ('paid', models.BooleanField(default=True)),
                ('invoice', models.FileField(null=True, upload_to='invoices/% Y/% m/% d/')),
                ('paylater_receipt', models.FileField(null=True, upload_to='paylater_receipts/% Y/% m/% d/')),
                ('cancelled', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('paylater', models.BooleanField(default=False)),
                ('paylater_date', models.DateField(blank=True, null=True, verbose_name='Pay Later Date')),
                ('removed', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_customer_id', to=settings.AUTH_USER_MODEL)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_seller_id', to=settings.AUTH_USER_MODEL)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_shop_id', to='products.shops')),
            ],
        ),
        migrations.CreateModel(
            name='roomBookings',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_from', models.DateField()),
                ('booked_till', models.DateField()),
                ('duration', models.IntegerField()),
                ('currency', models.CharField(max_length=255)),
                ('cost', models.BigIntegerField()),
                ('price_to_be_paid', models.BigIntegerField()),
                ('discount', models.IntegerField()),
                ('paid', models.BooleanField(default=True)),
                ('invoice', models.FileField(null=True, upload_to='invoices/% Y/% m/% d/')),
                ('paylater_receipt', models.FileField(null=True, upload_to='paylater_receipts/% Y/% m/% d/')),
                ('cancelled', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('paylater', models.BooleanField(default=False)),
                ('paylater_date', models.DateField(blank=True, null=True, verbose_name='Pay Later Date')),
                ('removed', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_customer_id', to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_room_id', to='products.rooms')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_seller_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='apartmentBookings',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_from', models.DateField()),
                ('booked_till', models.DateField()),
                ('duration', models.IntegerField()),
                ('currency', models.CharField(max_length=255)),
                ('cost', models.BigIntegerField()),
                ('price_to_be_paid', models.BigIntegerField()),
                ('discount', models.IntegerField()),
                ('paid', models.BooleanField(default=True)),
                ('invoice', models.FileField(null=True, upload_to='invoices/% Y/% m/% d/')),
                ('paylater_receipt', models.FileField(null=True, upload_to='paylater_receipts/% Y/% m/% d/')),
                ('cancelled', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('paylater', models.BooleanField(default=False)),
                ('paylater_date', models.DateField(blank=True, null=True, verbose_name='Pay Later Date')),
                ('removed', models.BooleanField(default=False)),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_apartment_id', to='products.apartments')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartment_customer_id', to=settings.AUTH_USER_MODEL)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartment_seller_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
