# Generated by Django 3.1.4 on 2021-02-18 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roomBookings',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_from', models.DateField()),
                ('booked_till', models.DateField()),
                ('capacity', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile', models.BigIntegerField()),
                ('alternate_mobile', models.BigIntegerField(blank=True, null=True)),
                ('country_code', models.CharField(max_length=255)),
                ('wifi', models.BooleanField()),
                ('house_TV', models.BooleanField()),
                ('room_TV', models.BooleanField()),
                ('house_refridgerator', models.BooleanField()),
                ('room_refridgerator', models.BooleanField()),
                ('purified_water', models.BooleanField()),
                ('geyser', models.BooleanField()),
                ('AC', models.BooleanField()),
                ('cooler', models.BooleanField()),
                ('breakfast', models.BooleanField()),
                ('lunch', models.BooleanField()),
                ('dinner', models.BooleanField()),
                ('currency', models.CharField(max_length=255)),
                ('savings', models.IntegerField()),
                ('cost', models.BigIntegerField()),
                ('price_to_be_paid', models.BigIntegerField()),
                ('discount', models.IntegerField()),
                ('coupon', models.CharField(blank=True, max_length=255, null=True)),
                ('paid', models.BooleanField(default=True)),
                ('seller_pay', models.BigIntegerField()),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/% Y/% m/% d/')),
                ('cancelled', models.BooleanField(default=False)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('extended', models.BooleanField(default=False)),
                ('is_extended', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('refund_amount', models.IntegerField(default=0)),
                ('paylater', models.BooleanField(default=False)),
                ('paylater_date', models.DateField(blank=True, null=True, verbose_name='Pay Later Date')),
                ('ended', models.BooleanField(default=False)),
            ],
        ),
    ]
