# Generated by Django 3.1.4 on 2021-02-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20210205_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombookings',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/% Y/% m/% d/'),
        ),
    ]
