# Generated by Django 3.1.4 on 2021-02-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20210218_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookings',
            name='room_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roombookings',
            name='seller_review',
            field=models.BooleanField(default=False),
        ),
    ]
