# Generated by Django 3.1.4 on 2021-02-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20210207_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombookings',
            name='booked_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roombookings',
            name='booked_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
