# Generated by Django 3.1.4 on 2021-02-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20210220_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombookings',
            name='seller_review',
        ),
    ]
