# Generated by Django 3.1.4 on 2021-02-20 10:51

import bookings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_delete_room_rating_and_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0004_remove_roombookings_seller_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_rating_and_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('reviews', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('photo1', models.ImageField(default='/images/rooms/default.jpg', upload_to=bookings.models.upload_to_roomreviews)),
                ('photo2', models.ImageField(default='/images/rooms/default.jpg', upload_to=bookings.models.upload_to_roomreviews)),
                ('photo3', models.ImageField(default='/images/rooms/default.jpg', upload_to=bookings.models.upload_to_roomreviews)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_customer_my_id', to=settings.AUTH_USER_MODEL)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_my_id', to='products.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='room_rating_and_reviews',
            fields=[
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='bookings.roombookings')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('reviews', models.TextField()),
                ('photo1', models.ImageField(default='/images/rooms/default.jpg', upload_to=bookings.models.upload_to_roomreviews)),
                ('photo2', models.ImageField(default='/images/rooms/default.jpg', upload_to=bookings.models.upload_to_roomreviews)),
                ('photo3', models.ImageField(default='/images/rooms/default.jpg', upload_to=bookings.models.upload_to_roomreviews)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_customer_my_id', to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_my_id', to='products.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='apartment_rating_and_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('reviews', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('photo1', models.ImageField(default='/images/rooms/default.jpg', upload_to=bookings.models.upload_to_roomreviews)),
                ('photo2', models.ImageField(default='/images/rooms/default.jpg', upload_to=bookings.models.upload_to_roomreviews)),
                ('photo3', models.ImageField(default='/images/rooms/default.jpg', upload_to=bookings.models.upload_to_roomreviews)),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartment_my_id', to='products.rooms')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartment_customer_my_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
