# Generated by Django 3.1.4 on 2021-02-07 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20210207_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombookings',
            name='booked_from',
            field=models.DateField(default=datetime.date(2021, 2, 7)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roombookings',
            name='booked_till',
            field=models.DateField(default=datetime.date(2021, 2, 7)),
            preserve_default=False,
        ),
    ]
