# Generated by Django 3.1.4 on 2021-02-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20210207_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookings',
            name='refund_amount',
            field=models.IntegerField(default=0),
        ),
    ]
