# Generated by Django 3.1.4 on 2021-02-21 08:22

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_apartment_rating_and_reviews_room_rating_and_reviews_shop_rating_and_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_rating_and_reviews',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to=bookings.models.upload_to_roomreviews),
        ),
        migrations.AlterField(
            model_name='room_rating_and_reviews',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=bookings.models.upload_to_roomreviews),
        ),
        migrations.AlterField(
            model_name='room_rating_and_reviews',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=bookings.models.upload_to_roomreviews),
        ),
    ]
