# Generated by Django 3.1.4 on 2021-02-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_roombookings_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookings',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
