# Generated by Django 3.1.4 on 2021-02-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_apartmentbookings_shopbookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentbookings',
            old_name='room_name',
            new_name='apartment_name',
        ),
    ]
