# Generated by Django 3.1.4 on 2021-02-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_roombookings_cancelled_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombookings',
            old_name='removed',
            new_name='ended',
        ),
    ]
