# Generated by Django 3.1.4 on 2021-02-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20210207_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookings',
            name='seller_pay',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
