# Generated by Django 3.1.4 on 2021-02-24 04:21

import bookings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_apartments_removable_laundry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0009_auto_20210224_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_rating_and_reviews',
            fields=[
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='bookings.shopbookings')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('reviews', models.TextField()),
                ('photo1', models.ImageField(blank=True, null=True, upload_to=bookings.models.upload_to_shopreviews)),
                ('photo2', models.ImageField(blank=True, null=True, upload_to=bookings.models.upload_to_shopreviews)),
                ('photo3', models.ImageField(blank=True, null=True, upload_to=bookings.models.upload_to_shopreviews)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_customer_my_id', to=settings.AUTH_USER_MODEL)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_my_id', to='products.shops')),
            ],
        ),
        migrations.CreateModel(
            name='apartment_rating_and_reviews',
            fields=[
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='bookings.apartmentbookings')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('reviews', models.TextField()),
                ('photo1', models.ImageField(blank=True, null=True, upload_to=bookings.models.upload_to_apartmentreviews)),
                ('photo2', models.ImageField(blank=True, null=True, upload_to=bookings.models.upload_to_apartmentreviews)),
                ('photo3', models.ImageField(blank=True, null=True, upload_to=bookings.models.upload_to_apartmentreviews)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartment_my_id', to='products.apartments')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartment_customer_my_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
