# Generated by Django 3.1.4 on 2021-02-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_roombookings_seller_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookings',
            name='room_name',
            field=models.CharField(default='my room', max_length=255),
            preserve_default=False,
        ),
    ]
