# Generated by Django 3.1.4 on 2021-03-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_apartment_rating_and_reviews_shop_rating_and_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookings',
            name='IFSC_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roombookings',
            name='acccount_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roombookings',
            name='account_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roombookings',
            name='bank_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roombookings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
