# Generated by Django 3.1.4 on 2021-02-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_roombookings_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookings',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roombookings',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
