# Generated by Django 3.1.4 on 2021-02-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20210212_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookings',
            name='extended',
            field=models.BooleanField(default=False),
        ),
    ]
