# Generated by Django 3.1.4 on 2021-02-13 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rooms_pausebooking'),
        ('bookings', '0012_roombookings_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookings',
            name='extended_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.rooms'),
        ),
    ]
