# Generated by Django 3.1.4 on 2021-02-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_roombookings_extended_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookings',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
    ]
