# Generated by Django 3.1.4 on 2021-03-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20210303_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbookings',
            name='payment_id',
            field=models.CharField(default='hy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombookings',
            name='payment_id',
            field=models.CharField(default='hy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopbookings',
            name='payment_id',
            field=models.CharField(default='hy', max_length=255),
            preserve_default=False,
        ),
    ]
