# Generated by Django 3.1.4 on 2021-02-13 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_roombookings_is_extended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombookings',
            name='extended_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bookings.roombookings'),
        ),
    ]
