# Generated by Django 3.1.4 on 2021-05-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_auto_20210326_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentbookings',
            name='seller_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roombookings',
            name='seller_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopbookings',
            name='seller_paid',
            field=models.BooleanField(default=False),
        ),
    ]
