# Generated by Django 3.1.4 on 2021-06-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_auto_20210529_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombookings',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
